version: "3.9"
services:
  api:
    build: .
    env_file: .env.prod
    restart: always
    container_name: 'rafael-api'
    ports:
      - "8000:8000"
#    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
