apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2023-03-10T07:56:34.000Z
  labels:
    app: rafael-api-pod
  name: rafael-api-pod
spec:
  containers:
  - env:
    - name: MONGO_URL
      value: cresco-mgdb04.portici.enea.it
    - name: MONGO_PASS
      value: T3mPass
    - name: ACCESS_TOKEN_EXPIRE_MINUTES
      value: "30"
    - name: HOSTNAME
      value: 323202b47eae
    - name: MONGO_PORT
      value: "27017"
    - name: SECRET_KEY
      value: 6fb68bb35d6d21c119056fbe7bc2b4f6c2da700e75e1976f87e820132d5217e0
    - name: ALGORITHM
      value: H256
    - name: MONGO_DB
      value: rafael
    - name: HOME
      value: /root
    - name: MONGO_USER
      value: rafavatar
    image: docker.io/mpuccini/rafael-api:latest
    name: rafael-api-podified
    ports:
    - containerPort: 8000
      hostPort: 8000
    resources: {}
  hostname: rafael-api-pod
  restartPolicy: Always
status: {}